FROM node:22-alpine AS build
WORKDIR /app
COPY src/frontend/package.json ./package.json
RUN npm install --ignore-scripts
COPY src/frontend ./
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
